---
# Use this for linux
# - name: Install pip
#   apt:
#     name: python-pip
#     state: present
# Use this for OSX
- name: Easy install of pip
  easy_install:
    name: pip
    state: present
- name: Install docker-py for ansible docker module
  pip:
    name: "docker-py>=1.7.0"
    state: present
    version: yes
- name: Create docker network
  docker_network:
    name: influxdb
- name: Create Grafana container
  docker_container:
    name: grafana
    detach: yes
    image: grafana:team9
    state: started
    pull: false
    ports:
    - "3000:3000"
    networks:
    - name: influxdb